Repository ibexa/recipes, pull requests merged in 2021-12, with the labels that each got.

#48 IBX-71: Added Taxonomy to ibexa/content
  ibexa/commerce/4.0.x-dev/manifest.json
  ibexa/content-tree/4.0.x-dev/manifest.json
  ibexa/content/4.0.x-dev/config/packages/ibexa_taxonomy.yaml
  ibexa/content/4.0.x-dev/config/routes/ibexa_taxonomy.yaml
  ibexa/content/4.0.x-dev/manifest.json
  ibexa/experience/4.0.x-dev/manifest.json
  ibexa/taxonomy/4.0.x-dev/manifest.json
  ibexa/tree-builder/4.0.x-dev/manifest.json
Labels: Feature

#49 [ibexa/docker] Added recipes for 0.2 version series
  ibexa/docker/0.2.x-dev/manifest.json
Labels: Ready for review

#56 IBX-1693: Added missing Taxonomy config files
  ibexa/commerce/4.0.x-dev/config/packages/ibexa_taxonomy.yaml
  ibexa/commerce/4.0.x-dev/config/routes/ibexa_taxonomy.yaml
  ibexa/experience/4.0.x-dev/config/packages/ibexa_taxonomy.yaml
  ibexa/experience/4.0.x-dev/config/routes/ibexa_taxonomy.yaml
Labels: Bug

#59 IBX-568: Added REST routes for Product Catalog
  ibexa/commerce/4.0.x-dev/config/routes/ibexa_product_catalog.yaml
Labels: Feature

#60 [ibexa/docker] IBX-1550: Updated default Selenium image
  ibexa/docker/0.1.x-dev/manifest.json
  ibexa/docker/0.2.x-dev/manifest.json
Labels: Ready for review
