Repository ibexa/recipes, pull requests merged in 2021-01, with the labels that each got.

#7 [ibexa/*] Enabled IbexaPlatformInstallerBundle
  ibexa/commerce/dev-master/manifest.json
  ibexa/content/3.3.x-dev/manifest.json
  ibexa/experience/3.3.x-dev/manifest.json
Labels: enhancement

#9 Fixed size and color's index_field in ezcommerce_demo.yaml for all product editions
  ibexa/commerce/dev-master/config/packages/ezcommerce/ezcommerce_demo.yaml
  ibexa/content/3.3.x-dev/config/packages/ezcommerce/ezcommerce_demo.yaml
  ibexa/experience/3.3.x-dev/config/packages/ezcommerce/ezcommerce_demo.yaml
Labels: bug

#12 [ibexa/*] Updated version of sass-loader
  ibexa/commerce/3.3/encore/package.json
  ibexa/commerce/dev-master/encore/package.json
  ibexa/content/3.3.x-dev/encore/package.json
  ibexa/content/3.3/encore/package.json
  ibexa/experience/3.3.x-dev/encore/package.json
  ibexa/experience/3.3/encore/package.json
  ibexa/oss/3.3.x-dev/encore/package.json
  ibexa/oss/3.3/encore/package.json
Labels: Bug, QA approved
