Repository ibexa/recipes, pull requests merged in 2022-02, with the labels that each got.

#85 [ibexa/content] Added Taxonomy REST routes
  ibexa/commerce/4.0.x-dev/config/routes/ibexa_taxonomy.yaml
  ibexa/content/4.0.x-dev/config/routes/ibexa_taxonomy.yaml
  ibexa/experience/4.0.x-dev/config/routes/ibexa_taxonomy.yaml
Labels: Bug, Ready for review

#88 IBX-2224: Added TRUSTED_PROXIES env
  ibexa/commerce/4.0.x-dev/manifest.json
  ibexa/content/4.0.x-dev/manifest.json
  ibexa/experience/4.0.x-dev/manifest.json
  ibexa/oss/4.0.x-dev/manifest.json
Labels: Bug, QA approved, Ready for review

#92 IBX-2299: Fixed asset generation order to prevent issues on missing manifest file
  ibexa/commerce/3.3.x-dev/config/packages/ezplatform_assets.yaml
  ibexa/commerce/3.3.x-dev/encore/webpack.config.js
  ibexa/commerce/3.3.x-dev/manifest.json
  ibexa/commerce/4.0.x-dev/config/packages/ibexa_assets.yaml
  ibexa/commerce/4.0.x-dev/encore/webpack.config.js
  ibexa/commerce/4.0.x-dev/manifest.json
  ibexa/content/3.3.x-dev/config/packages/ezplatform_assets.yaml
  ibexa/content/3.3.x-dev/encore/webpack.config.js
  ibexa/content/3.3.x-dev/manifest.json
  ibexa/content/4.0.x-dev/config/packages/ibexa_assets.yaml
  ibexa/content/4.0.x-dev/encore/webpack.config.js
  ibexa/content/4.0.x-dev/manifest.json
  ibexa/experience/3.3.x-dev/config/packages/ezplatform_assets.yaml
  ibexa/experience/3.3.x-dev/encore/webpack.config.js
  ibexa/experience/3.3.x-dev/manifest.json
  ibexa/experience/4.0.x-dev/config/packages/ibexa_assets.yaml
  ibexa/experience/4.0.x-dev/encore/webpack.config.js
  ibexa/experience/4.0.x-dev/manifest.json
  ibexa/oss/3.3.x-dev/config/packages/ezplatform_assets.yaml
  ibexa/oss/3.3.x-dev/encore/webpack.config.js
  ibexa/oss/3.3.x-dev/manifest.json
  ibexa/oss/4.0.x-dev/config/packages/ibexa_assets.yaml
  ibexa/oss/4.0.x-dev/encore/webpack.config.js
  ibexa/oss/4.0.x-dev/manifest.json
Labels: Bug, Ready for review

#93 [ibx/*] Changed node-sass to dart-sass
  ibexa/commerce/3.3.x-dev/encore/package.json
  ibexa/commerce/4.0.x-dev/encore/package.json
  ibexa/content/3.3.x-dev/encore/package.json
  ibexa/content/4.0.x-dev/encore/package.json
  ibexa/experience/3.3.x-dev/encore/package.json
  ibexa/experience/4.0.x-dev/encore/package.json
  ibexa/oss/3.3.x-dev/encore/package.json
  ibexa/oss/4.0.x-dev/encore/package.json
Labels: QA approved

#96 [doctrine/annotations] IBX-2358: Added 1.10 recipe override to prevent issues with unsupported structure
  doctrine/annotations/1.10/config/routes/annotations.yaml
  doctrine/annotations/1.10/manifest.json
Labels: Bug, Ready for review

#99 Added Symfony serverless workflows
  .github/workflows/flex-update-achived.yml
  .github/workflows/flex-update.yml
Labels: Ready for review
